version: '3'
services:

  postgres:
    env_file:
      - .env
    image: postgres:9.6
    ports:
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    volumes:
      - ./data:/var/lib/postgresql/data/data

  pgadmin:
    build:
      context: ./postgres
      dockerfile: Dockerfile-pgadmin
    env_file:
      - .env
    ports:
      - '${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}'

  elasticsearch:
    env_file:
      - .env
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    ports:
      - '${ELASTICSEARCH_HOST_PORT}:${ELASTICSEARCH_CONTAINER_PORT}'
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
