version: '3'
services:

  jupyter:
    env_file:
      - .env
    build:
      context: ./jupyter
    ports:
      - '${JUPYTER_HOST_PORT}:${JUPYTER_CONTAINER_PORT}'
    volumes:
      - .:/code
      - ./jupyter/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py

  postgres:
    env_file:
      - .env
    image: postgres:10
    ports:
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    volumes:
      - ./data:/data

  pgadmin:
    build:
      context: ./postgres
      dockerfile: Dockerfile-pgadmin
    env_file:
      - .env
    ports:
      - '${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}'

  mysql:
    env_file:
      - .env
    image: mysql:5.7
    ports:
      - '${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}'
    volumes:
      - ./data:/data

  phpmyadmin:
    env_file:
      - .env
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '${MYSQL_PHPMYADMIN_HOST_PORT}:${MYSQL_PHPMYADMIN_CONTAINER_PORT}'

  elasticsearch:
    env_file:
      - .env
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    ports:
      - '${ELASTICSEARCH_HOST_PORT}:${ELASTICSEARCH_CONTAINER_PORT}'
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
