version: '3'
services:

  jupyter:
      build:
        context: ./jupyter
      env_file:
        - .env
        - .env.secret
      ports:
        - '${JUPYTER_HOST_PORT}:${JUPYTER_CONTAINER_PORT}'
      volumes:
        - .:/code
        - ./jupyter/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py

  postgres:
    env_file:
      - .env
      - .env.secret
    image: postgres:10
    ports:
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    volumes:
      - .:/code

  pgadmin:
    build:
      context: ./postgres
      dockerfile: Dockerfile-pgadmin
    env_file:
      - .env
      - .env.secret
    ports:
      - '${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}'
