FROM python:2-alpine
MAINTAINER Tobin Quadros
# Initial attribution goes to https://github.com/thaJeztah/pgadmin4-docker

LABEL component-id=pgadmin

ENV PGADMIN_VERSION=1.5
ENV PYTHONDONTWRITEBYTECODE=1

RUN apk add --no-cache alpine-sdk postgresql-dev \
 && echo "https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v${PGADMIN_VERSION}/pip/pgadmin4-${PGADMIN_VERSION}-py2.py3-none-any.whl" > requirements.txt \
 && pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt \
 && apk del alpine-sdk

RUN addgroup -g 50 -S pgadmin \
 && adduser -D -S -h /pgadmin -s /sbin/nologin -u 1000 -G pgadmin pgadmin \
 && mkdir -p /pgadmin/config /pgadmin/storage; \
 chown -R 1000:50 /pgadmin

COPY config_local.py /usr/local/lib/python2.7/site-packages/pgadmin4/

EXPOSE 5050

USER pgadmin
CMD [ "python", "./usr/local/lib/python2.7/site-packages/pgadmin4/pgAdmin4.py" ]
VOLUME /pgadmin/
